name: CI-CD Pipeline

on:
  push:
    branches:
      - feature/login
  pull_request:
    branches:
      - feature/login

jobs:
  build-and-test:
    runs-on: self-hosted

    steps:
      - name: Clonar repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Marcar inicio del despliegue
        run: echo "START_TIME=$(date +%s)" >> $GITHUB_ENV

      - name: Instalar Node 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Instalar dependencias
        run: npm install

      - name: Correr tests con cobertura
        run: npm test -- --coverage

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}
          
        

      - name: Enviar cobertura a CloudWatch
        run: |
          COVERAGE=$(node -p "require('./coverage/coverage-summary.json').total.lines.pct")
          echo "Cobertura: $COVERAGE%"
          aws cloudwatch put-metric-data --namespace "MicroservicioNotas" --metric-name "CoveragePercent" --value "$COVERAGE" --unit Percent

      - name: Auditoria local de calidad
        run: |
          echo "Revisando calidad del codigo..."
          if [ ! -f "coverage/lcov.info" ]; then
            echo "Error: No hay reporte de cobertura de Jest."
            exit 1
          fi
          echo "Calidad aprobada. Cero errores criticos."

      - name: Auditoria de seguridad (npm audit)
        run: npm audit --audit-level=critical

      - name: Crear imagen Docker
        run: docker build -t notas-api .

      - name: Validar Docker Compose
        run: docker compose config

      - name: Deploy automatico a Render
        if: github.event_name == 'push' && github.ref == 'refs/heads/feature/login'
        run: |
          curl -X POST "https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}"

      - name: Enviar tiempo de despliegue a CloudWatch
        run: |
          END_TIME=$(date +%s)
          DURATION=$((END_TIME - START_TIME))
          echo "Duracion del pipeline: $DURATION segundos"
          aws cloudwatch put-metric-data --namespace "MicroservicioNotas" --metric-name "DeploymentTimeSeconds" --value "$DURATION" --unit Seconds
